export const ACTION_ADD_USER = "ACTION_ADD_USER";
export const ACTION_ADD_CURRENT_DAY_DATE = "ACTION_ADD_CURRENT_DAY_DATE";
export const ACTION_ADD_TASKS = "ACTION_ADD_TASKS";
export const ACTION_ADD_CURRENT_DAY_TASKS = "ACTION_ADD_CURRENT_DAY_TASKS";
export const ACTION_ADD_NEW_TASK = "ACTION_ADD_NEW_TASK";
export const ACTION_SWITCH_SHOWED_TASKS_LIST =
  "ACTION_SWITCH_SHOWED_TASKS_LIST";
export const ACTION_CHECK_TASK = "ACTION_CHECK_TASK";
export const ACTION_ADD_CURRENT_MONTH_TASKS = "ACTION_ADD_CURRENT_MONTH_TASKS";
export const ACTION_PUT_POPUP_COORDINATES = "ACTION_PUT_POPUP_COORDINATES";
