export const ACTION_ADD_CURRENT_DAY_DATE = "ACTION_ADD_CURRENT_DAY_DATE";
export const ACTION_ADD_TASKS = "ACTION_ADD_TASKS";
export const ACTION_ADD_CURRENT_DAY_TASKS = "ACTION_ADD_CURRENT_DAY_TASKS";
export const ACTION_ADD_NEW_TASK = 'ACTION_ADD_NEW_TASK';